[build-system]
requires = ["setuptools", "wheel", "ninja", "torch"]
build-backend = "setuptools.build_meta"

[project]
name = "dyt_cuda"
version = "0.1.0"
description = "CUDA kernels for DyT"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "torch",
]